language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - nightly

env:
  global:
    - CORE_BRANCH=master
    - APP_NAME=encryption
  matrix:
    - DB=sqlite

branches:
  only:
    - master
    - /^stable\d+(\.\d+)?$/

before_install:
  - wget https://raw.githubusercontent.com/owncloud/administration/master/travis-ci/before_install.sh
  - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB

  # Add some output debugging information
  - cd ../core
  - ./occ check
  - ./occ status
  - ./occ app:list
  - ./occ app:enable $APP_NAME
  - ./occ app:list

script:
  # Test the app
  - cd apps/$APP_NAME/
  - sh -c "if [ '$CODECHECK' = '1' ]; then find . -name \*.php -exec php -l \"{}\" \;; fi"
  - cd ../../
  - sh -c "if [ '$CODECHECK' = '1' ]; then ./occ app:check-code $APP_NAME -c private -c strong-comparison; fi"
  - sh -c "if [ '$CODECHECK' = '2' ]; then ./occ app:check-code $APP_NAME -c deprecation; fi"
  - cd apps/$APP_NAME/

  # Run phpunit tests
  - cd tests
  - sh -c "if [ '$INTEGRATION' != '1' -a '$JSTESTS' != '1' -a '$CODECHECK' != '1' -a '$CODECHECK' != '2' ]; then ../../../lib/composer/bin/phpunit --configuration phpunit.xml; fi"
  - cd ..

  # Create coverage report
  - cd tests
  - sh -c "if [ '$INTEGRATION' != '1' -a '$JSTESTS' != '1' -a '$CODECHECK' != '1' -a '$CODECHECK' != '2' -a '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then wget https://scrutinizer-ci.com/ocular.phar; fi"
  - sh -c "if [ '$INTEGRATION' != '1' -a '$JSTESTS' != '1' -a '$CODECHECK' != '1' -a '$CODECHECK' != '2' -a '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then php ocular.phar code-coverage:upload --format=php-clover clover.xml; fi"
  - cd ..

matrix:
  include:
#    - php: 5.6
#      env: DB=mysql CORE_BRANCH=stable10
#    - php: 5.6
#      env: DB=mysql CODECHECK=1
    - php: 5.6
      env: DB=mysql CODECHECK=2
  allow_failures:
    - php: nightly
  fast_finish: true
